"""Backward-compatibility re-export shim.

All prompt constants have been moved to individual files under prompts/.
Import directly from the specific module instead, e.g.:
    from .prompts.cardiology import CARDIOLOGY_INSTRUCTION
"""

from .shared import (
    _SAFETY_DISCLAIMER,
    _TOOL_PROTOCOL,
    _CLINICAL_REASONING,
    _IMAGE_ANALYSIS_WORKFLOW,
)
from .coordinator import COORDINATOR_INSTRUCTION
from .allergy_immunology import ALLERGY_IMMUNOLOGY_INSTRUCTION
from .anesthesiology import ANESTHESIOLOGY_INSTRUCTION
from .cardiology import CARDIOLOGY_INSTRUCTION
from .cardiothoracic_surgery import CARDIOTHORACIC_SURGERY_INSTRUCTION
from .colorectal_surgery import COLORECTAL_SURGERY_INSTRUCTION
from .critical_care import CRITICAL_CARE_INSTRUCTION
from .dermatology import DERMATOLOGY_INSTRUCTION
from .discharge_planning import DISCHARGE_PLANNING_INSTRUCTION
from .emergency_medicine import EMERGENCY_MEDICINE_INSTRUCTION
from .endocrinology import ENDOCRINOLOGY_INSTRUCTION
from .ent import ENT_INSTRUCTION
from .gastroenterology import GASTROENTEROLOGY_INSTRUCTION
from .general_medicine import GENERAL_MEDICINE_INSTRUCTION
from .general_surgery import GENERAL_SURGERY_INSTRUCTION
from .gynecology import GYNECOLOGY_INSTRUCTION
from .hematology import HEMATOLOGY_INSTRUCTION
from .infectious_diseases import INFECTIOUS_DISEASES_INSTRUCTION
from .nephrology import NEPHROLOGY_INSTRUCTION
from .neurology import NEUROLOGY_INSTRUCTION
from .neurosurgery import NEUROSURGERY_INSTRUCTION
from .nuclear_medicine import NUCLEAR_MEDICINE_INSTRUCTION
from .oncology import ONCOLOGY_INSTRUCTION
from .ophthalmology import OPHTHALMOLOGY_INSTRUCTION
from .orthopedics import ORTHOPEDICS_INSTRUCTION
from .pathology import PATHOLOGY_INSTRUCTION
from .pediatrics import PEDIATRICS_INSTRUCTION
from .pharmacy import PHARMACY_INSTRUCTION
from .physical_medicine_rehab import PHYSICAL_MEDICINE_REHAB_INSTRUCTION
from .plastic_surgery import PLASTIC_SURGERY_INSTRUCTION
from .psychology import PSYCHOLOGY_INSTRUCTION
from .pulmonology import PULMONOLOGY_INSTRUCTION
from .radiation_oncology import RADIATION_ONCOLOGY_INSTRUCTION
from .radiology import RADIOLOGY_INSTRUCTION
from .rheumatology import RHEUMATOLOGY_INSTRUCTION
from .thoracic_surgery import THORACIC_SURGERY_INSTRUCTION
from .urology import UROLOGY_INSTRUCTION
from .vascular_surgery import VASCULAR_SURGERY_INSTRUCTION

__all__ = [
    "_SAFETY_DISCLAIMER",
    "_TOOL_PROTOCOL",
    "_CLINICAL_REASONING",
    "_IMAGE_ANALYSIS_WORKFLOW",
    "COORDINATOR_INSTRUCTION",
    "ALLERGY_IMMUNOLOGY_INSTRUCTION",
    "ANESTHESIOLOGY_INSTRUCTION",
    "CARDIOLOGY_INSTRUCTION",
    "CARDIOTHORACIC_SURGERY_INSTRUCTION",
    "COLORECTAL_SURGERY_INSTRUCTION",
    "CRITICAL_CARE_INSTRUCTION",
    "DERMATOLOGY_INSTRUCTION",
    "DISCHARGE_PLANNING_INSTRUCTION",
    "EMERGENCY_MEDICINE_INSTRUCTION",
    "ENDOCRINOLOGY_INSTRUCTION",
    "ENT_INSTRUCTION",
    "GASTROENTEROLOGY_INSTRUCTION",
    "GENERAL_MEDICINE_INSTRUCTION",
    "GENERAL_SURGERY_INSTRUCTION",
    "GYNECOLOGY_INSTRUCTION",
    "HEMATOLOGY_INSTRUCTION",
    "INFECTIOUS_DISEASES_INSTRUCTION",
    "NEPHROLOGY_INSTRUCTION",
    "NEUROLOGY_INSTRUCTION",
    "NEUROSURGERY_INSTRUCTION",
    "NUCLEAR_MEDICINE_INSTRUCTION",
    "ONCOLOGY_INSTRUCTION",
    "OPHTHALMOLOGY_INSTRUCTION",
    "ORTHOPEDICS_INSTRUCTION",
    "PATHOLOGY_INSTRUCTION",
    "PEDIATRICS_INSTRUCTION",
    "PHARMACY_INSTRUCTION",
    "PHYSICAL_MEDICINE_REHAB_INSTRUCTION",
    "PLASTIC_SURGERY_INSTRUCTION",
    "PSYCHOLOGY_INSTRUCTION",
    "PULMONOLOGY_INSTRUCTION",
    "RADIATION_ONCOLOGY_INSTRUCTION",
    "RADIOLOGY_INSTRUCTION",
    "RHEUMATOLOGY_INSTRUCTION",
    "THORACIC_SURGERY_INSTRUCTION",
    "UROLOGY_INSTRUCTION",
    "VASCULAR_SURGERY_INSTRUCTION",
]
